<?php $collection = $block->getCollection(); ?>

<?php if (count($collection)) { ?>
<table border="1">
    <thead>
        <td>ID</td>
        <td>Name</td>
        <td></td>
    </thead>
    <tbody>
      <?php foreach($collection as $post){ ?>
        <tr>
           <td><?php echo $post->getId(); ?></td> 
           <td><?php echo $post->getName(); ?></td>
           <td><a href="<?= $block->getUrl('testmodal/thuan/edit', ['id' => ($post->getId())])?>">Edit </a><a href="<?= $block->getUrl('testmodal/thuan/delete', ['id' => ($post->getId())])?>">Delete</a></td>
        </tr>
     <?php } ?>
    </tbody>
</table>
<?php } else { ?>
    <h1 style="color: red">No Data founded</h1>
<?php } ?>
<hr />
<form method="post" action="<?= $block->getPostUrl() ?>">
    <fieldset style="margin: 0 auto; width: 50%">
        <div>
            <label for="name"><?= __("Name") ?></label>
            <input type="text" name="name">
        </div> <br/>
        <input type="submit" value="Add" />
    </fieldset>
</form>